'use client';

import { useDashboard } from '@/context/DashboardContext';
import { useState } from 'react';
import { motion } from 'framer-motion';

export default function ExecutiveSummary() {
  const { data } = useDashboard();
  const [summary, setSummary] = useState("");
  const [loadingSummary, setLoadingSummary] = useState(false);

  const riskReduction = Math.round(((data.suppliers - data.riskSuppliers) / data.suppliers) * 100);
  const leadTimeSaved = Math.max(3, Math.floor(data.inventoryHealth / 8));
  const generateSummary = async () => {
    setLoadingSummary(true);
  
    try {
      const res = await fetch("/api/chat", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          message: `
  Generate an executive supply chain summary.
  
  Inventory Health: ${data.inventoryHealth}%
  Total Suppliers: ${data.suppliers}
  Risk Suppliers: ${data.riskSuppliers}
  Potential Savings: ${data.potentialSavings}
  
  Provide:
  1. Current Supply Chain Health
  2. Key Risks
  3. Cost Saving Opportunities
  4. Recommended Actions
  Give ans such that everything comes in chatbot area
  
  Keep response concise.
          `,
        }),
      });
  
      const result = await res.json();
  
      setSummary(result.response || "Unable to generate summary");
    } catch {
      setSummary("Unable to generate summary");
    }
  
    setLoadingSummary(false);
  };

  return (
    <motion.div 
      initial={{ opacity: 0, y: 30 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.6, delay: 0.1, ease: [0.16, 1, 0.3, 1] }}
      whileHover={{ 
        borderColor: 'rgba(99, 102, 241, 0.4)',
        boxShadow: '0 0 40px rgba(99, 102, 241, 0.06)'
      }}
      // Rich asymmetric deep gradient background mapping
      className="w-full flex flex-col justify-between rounded-2xl border-2 border-slate-800/80 bg-gradient-to-br from-slate-900 via-[#0a0f24] to-[#020512] p-6 shadow-2xl relative overflow-hidden transition-all duration-500 group"
    >
      <div className="absolute -bottom-24 -right-24 w-56 h-56 bg-indigo-500/10 blur-[100px] rounded-full pointer-events-none group-hover:bg-indigo-500/10 transition-all duration-500" />

      <div className="relative z-10 w-full flex flex-col h-full justify-between gap-6">
        
        <div>
          <div className="flex items-center justify-between mb-5">
            <div>
              <h2 className="text-base font-extrabold text-white tracking-wide uppercase">AI Executive Summary</h2>
              <p className="text-[11px] text-indigo-400/80 font-semibold tracking-wider mt-0.5 uppercase">Strategic insights generated by AI</p>
            </div>
            <div className="rounded-full border border-indigo-500/30 bg-indigo-500/10 px-3 py-1 text-[10px] font-bold text-indigo-400 uppercase tracking-widest shadow-[0_0_15px_rgba(99,102,241,0.1)]">
              AI Core
            </div>
          </div>

          <motion.div 
            whileHover={{ backgroundColor: 'rgba(2, 6, 23, 0.4)', borderColor: 'rgba(99, 102, 241, 0.2)' }}
            className="rounded-xl border border-slate-800 bg-slate-950/40 p-5 border-l-4 border-l-indigo-500 transition-all duration-300"
          >
            {/* <p>...</p>
            <p>...</p> */}
            {!summary && !loadingSummary && (
  <motion.button
    whileHover={{ scale: 1.02 }}
    whileTap={{ scale: 0.98 }}
    onClick={generateSummary}
    className="mt-4 w-full rounded-xl bg-gradient-to-r from-indigo-500 to-cyan-500 py-3 text-sm font-bold text-white shadow-lg"
  >
    Generate AI Executive Summary
  </motion.button>
)}

{loadingSummary && (
  <div className="mt-4 rounded-xl border border-cyan-500/20 bg-cyan-500/5 p-4 text-cyan-400 text-sm font-semibold">
    Generating AI Insights...
  </div>
)}

{summary && (
  <div className="mt-4 rounded-xl border border-slate-800 bg-slate-950/40 p-4 text-sm text-slate-300 whitespace-pre-wrap">
    {summary}
  </div>
)}
          </motion.div>
        </div>

        {/* Bottom Mini Metrics Cards with spring physics scale transformations */}
        <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
          
          {/* Card 1 */}
          <motion.div 
            whileHover={{ 
              scale: 1.04, 
              borderColor: 'rgba(52, 211, 153, 0.4)',
              backgroundColor: 'rgba(15, 23, 42, 0.6)',
              boxShadow: '0 4px 20px rgba(52, 211, 153, 0.05)'
            }}
            transition={{ type: "spring", stiffness: 350, damping: 14 }}
            className="rounded-xl border border-slate-800 bg-slate-950/50 p-4 cursor-pointer transition-all duration-200"
          >
            <p className="text-[10px] font-bold text-slate-400 uppercase tracking-widest">Risk Reduction</p>
            <h3 className="mt-1 text-2xl font-black text-emerald-400">{riskReduction}%</h3>
          </motion.div>

          {/* Card 2 */}
          <motion.div 
            whileHover={{ 
              scale: 1.04, 
              borderColor: 'rgba(6, 182, 212, 0.4)',
              backgroundColor: 'rgba(15, 23, 42, 0.6)',
              boxShadow: '0 4px 20px rgba(6, 182, 212, 0.05)'
            }}
            transition={{ type: "spring", stiffness: 350, damping: 14 }}
            className="rounded-xl border border-slate-800 bg-slate-950/50 p-4 cursor-pointer transition-all duration-200"
          >
            <p className="text-[10px] font-bold text-slate-400 uppercase tracking-widest">Cost Savings</p>
            <h3 className="mt-1 text-2xl font-black text-cyan-400">{data.potentialSavings}</h3>
          </motion.div>

          {/* Card 3 */}
          <motion.div 
            whileHover={{ 
              scale: 1.04, 
              borderColor: 'rgba(250, 204, 21, 0.4)',
              backgroundColor: 'rgba(15, 23, 42, 0.6)',
              boxShadow: '0 4px 20px rgba(250, 204, 21, 0.05)'
            }}
            transition={{ type: "spring", stiffness: 350, damping: 14 }}
            className="rounded-xl border border-slate-800 bg-slate-950/50 p-4 cursor-pointer transition-all duration-200"
          >
            <p className="text-[10px] font-bold text-slate-400 uppercase tracking-widest">Lead Time Saved</p>
            <h3 className="mt-1 text-2xl font-black text-yellow-400">{leadTimeSaved} Days</h3>
          </motion.div>

        </div>

      </div>
    </motion.div>
  );
}