'use client';

import { useDashboard } from '@/context/DashboardContext';
import { motion } from 'framer-motion';

export default function ExecutiveSummary() {
  const { data } = useDashboard();

  const riskReduction = Math.round(((data.suppliers - data.riskSuppliers) / data.suppliers) * 100);
  const leadTimeSaved = Math.max(3, Math.floor(data.inventoryHealth / 8));

  return (
    <motion.div 
      initial={{ opacity: 0, y: 30 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.6, delay: 0.1, ease: [0.16, 1, 0.3, 1] }}
      whileHover={{ 
        borderColor: 'rgba(99, 102, 241, 0.4)',
        boxShadow: '0 0 40px rgba(99, 102, 241, 0.06)'
      }}
      // Rich asymmetric deep gradient background mapping
      className="w-full flex flex-col justify-between rounded-2xl border-2 border-slate-800/80 bg-gradient-to-br from-slate-900 via-[#0a0f24] to-[#020512] p-6 shadow-2xl relative overflow-hidden transition-all duration-500 group"
    >
      <div className="absolute -bottom-24 -right-24 w-56 h-56 bg-indigo-500/10 blur-[100px] rounded-full pointer-events-none group-hover:bg-indigo-500/10 transition-all duration-500" />

      <div className="relative z-10 w-full flex flex-col h-full justify-between gap-6">
        
        <div>
          <div className="flex items-center justify-between mb-5">
            <div>
              <h2 className="text-base font-extrabold text-white tracking-wide uppercase">AI Executive Summary</h2>
              <p className="text-[11px] text-indigo-400/80 font-semibold tracking-wider mt-0.5 uppercase">Strategic insights generated by AI</p>
            </div>
            <div className="rounded-full border border-indigo-500/30 bg-indigo-500/10 px-3 py-1 text-[10px] font-bold text-indigo-400 uppercase tracking-widest shadow-[0_0_15px_rgba(99,102,241,0.1)]">
              AI Core
            </div>
          </div>

          <motion.div 
            whileHover={{ backgroundColor: 'rgba(2, 6, 23, 0.4)', borderColor: 'rgba(99, 102, 241, 0.2)' }}
            className="rounded-xl border border-slate-800 bg-slate-950/40 p-5 border-l-4 border-l-indigo-500 transition-all duration-300"
          >
            <p className="text-xs md:text-sm leading-relaxed text-slate-300">
              Current supply chain health score stands at{' '}
              <span className="font-extrabold text-cyan-400">{data.inventoryHealth}%</span>. 
              AI analysis has identified{' '}
              <span className="font-extrabold text-red-400">{data.riskSuppliers}</span> suppliers 
              requiring proactive monitoring due to elevated logistics, sourcing and operational risks. 
              The supplier network currently spans{' '}
              <span className="font-bold text-white">{data.suppliers}</span> active partners across multiple regions.
            </p>
            <p className="mt-4 text-xs md:text-sm leading-relaxed text-slate-300 border-t border-slate-800/60 pt-4">
              Based on current risk exposure and inventory conditions, AI recommends diversifying procurement channels, strengthening inventory buffers and prioritizing low-risk supplier regions. Estimated optimization potential remains at <span className="font-extrabold text-emerald-400">{data.potentialSavings}</span>.
            </p>
          </motion.div>
        </div>

        {/* Bottom Mini Metrics Cards with spring physics scale transformations */}
        <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
          
          {/* Card 1 */}
          <motion.div 
            whileHover={{ 
              scale: 1.04, 
              borderColor: 'rgba(52, 211, 153, 0.4)',
              backgroundColor: 'rgba(15, 23, 42, 0.6)',
              boxShadow: '0 4px 20px rgba(52, 211, 153, 0.05)'
            }}
            transition={{ type: "spring", stiffness: 350, damping: 14 }}
            className="rounded-xl border border-slate-800 bg-slate-950/50 p-4 cursor-pointer transition-all duration-200"
          >
            <p className="text-[10px] font-bold text-slate-400 uppercase tracking-widest">Risk Reduction</p>
            <h3 className="mt-1 text-2xl font-black text-emerald-400">{riskReduction}%</h3>
          </motion.div>

          {/* Card 2 */}
          <motion.div 
            whileHover={{ 
              scale: 1.04, 
              borderColor: 'rgba(6, 182, 212, 0.4)',
              backgroundColor: 'rgba(15, 23, 42, 0.6)',
              boxShadow: '0 4px 20px rgba(6, 182, 212, 0.05)'
            }}
            transition={{ type: "spring", stiffness: 350, damping: 14 }}
            className="rounded-xl border border-slate-800 bg-slate-950/50 p-4 cursor-pointer transition-all duration-200"
          >
            <p className="text-[10px] font-bold text-slate-400 uppercase tracking-widest">Cost Savings</p>
            <h3 className="mt-1 text-2xl font-black text-cyan-400">{data.potentialSavings}</h3>
          </motion.div>

          {/* Card 3 */}
          <motion.div 
            whileHover={{ 
              scale: 1.04, 
              borderColor: 'rgba(250, 204, 21, 0.4)',
              backgroundColor: 'rgba(15, 23, 42, 0.6)',
              boxShadow: '0 4px 20px rgba(250, 204, 21, 0.05)'
            }}
            transition={{ type: "spring", stiffness: 350, damping: 14 }}
            className="rounded-xl border border-slate-800 bg-slate-950/50 p-4 cursor-pointer transition-all duration-200"
          >
            <p className="text-[10px] font-bold text-slate-400 uppercase tracking-widest">Lead Time Saved</p>
            <h3 className="mt-1 text-2xl font-black text-yellow-400">{leadTimeSaved} Days</h3>
          </motion.div>

        </div>

      </div>
    </motion.div>
  );
}