'use client';

import { useDashboard } from '@/context/DashboardContext';

export default function ExecutiveSummary() {
  const { data } = useDashboard();

  const riskReduction = Math.round(
    ((data.suppliers - data.riskSuppliers) /
      data.suppliers) *
      100
  );

  const leadTimeSaved =
  Math.max(
    3,
    Math.floor(data.inventoryHealth / 8)
  );

  return (
    <div
      className="
        relative
        overflow-hidden
        rounded-3xl
        border
        border-cyan-500/20
        bg-slate-900/80
        backdrop-blur-xl
        p-6
        lg:p-8
        shadow-xl
        transition-all
        duration-500
        hover:shadow-[0_0_60px_rgba(6,182,212,0.08)]
      "
    >
      <div className="absolute inset-0 bg-gradient-to-br from-cyan-500/5 via-transparent to-transparent" />

      <div className="absolute -top-20 -right-20 h-64 w-64 rounded-full bg-cyan-500/10 blur-3xl" />

      <div className="relative z-10">

        <div className="flex items-center justify-between mb-6">
          <div>
            <h2 className="text-xl lg:text-2xl font-semibold text-white">
              AI Executive Summary
            </h2>

            <p className="text-slate-400 text-sm mt-1">
              Strategic insights generated by AI
            </p>
          </div>

          <div
            className="rounded-full border border-cyan-500/20 bg-cyan-500/10 px-4 py-1.5 text-xs font-medium text-cyan-400"
          >
            AI Generated
          </div>
        </div>

        <div
          className="
            rounded-3xl
            border
            border-slate-700/50
            bg-slate-800/40
            backdrop-blur-md
            p-6
          "
        >
          <p className="leading-8 text-slate-300">
  Current supply chain health score stands at{' '}
  <span className="font-semibold text-cyan-400">
    {data.inventoryHealth}%
  </span>
  . AI analysis has identified{' '}
  <span className="font-semibold text-white">
    {data.riskSuppliers}
  </span>{' '}
  suppliers requiring proactive monitoring due to elevated logistics,
  sourcing and operational risks. The supplier network currently spans{' '}
  <span className="font-semibold text-cyan-400">
    {data.suppliers}
  </span>{' '}
  active partners across multiple regions.
</p>

<p className="mt-4 leading-8 text-slate-300">
  Based on current risk exposure and inventory conditions, AI recommends
  diversifying procurement channels, strengthening inventory buffers and
  prioritizing low-risk supplier regions. Estimated optimization potential
  remains at{' '}
  <span className="font-semibold text-cyan-400">
    {data.potentialSavings}
  </span>
  , while maintaining service continuity and reducing supply-chain
  disruption risks.
</p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-5 mt-8">

          <div
            className="
              group
              relative
              overflow-hidden
              rounded-3xl
              border
              border-green-500/20
              bg-gradient-to-br
              from-slate-800/90
              via-slate-900/90
              to-slate-950/90
              p-5
            "
          >
            <div className="relative z-10">
              <p className="text-sm text-slate-400">
                Risk Reduction
              </p>

              <h3 className="mt-2 text-3xl font-bold text-green-400">
                {riskReduction}%
              </h3>
            </div>
          </div>

          <div
            className="
              group
              relative
              overflow-hidden
              rounded-3xl
              border
              border-cyan-500/20
              bg-gradient-to-br
              from-slate-800/90
              via-slate-900/90
              to-slate-950/90
              p-5
            "
          >
            <div className="relative z-10">
              <p className="text-sm text-slate-400">
                Cost Savings
              </p>

              <h3 className="mt-2 text-3xl font-bold text-cyan-400">
                {data.potentialSavings}
              </h3>
            </div>
          </div>

          <div
            className="
              group
              relative
              overflow-hidden
              rounded-3xl
              border
              border-yellow-500/20
              bg-gradient-to-br
              from-slate-800/90
              via-slate-900/90
              to-slate-950/90
              p-5
            "
          >
            <div className="relative z-10">
              <p className="text-sm text-slate-400">
                Lead Time Saved
              </p>

              <h3 className="mt-2 text-3xl font-bold text-yellow-400">
                {leadTimeSaved} Days
              </h3>
            </div>
          </div>

        </div>
      </div>
    </div>
  );
}